-- Expanded nutrients and food/supplement category

-- Add category column
ALTER TABLE foods ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'food'
  CHECK (category IN ('food', 'supplement'));

-- Vitamins
ALTER TABLE foods ADD COLUMN IF NOT EXISTS vitamin_a REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS vitamin_c REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS vitamin_e REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS vitamin_k REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS thiamin REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS riboflavin REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS niacin REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS vitamin_b6 REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS folate REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS vitamin_b12 REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS choline REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS retinol REAL;

-- Minerals
ALTER TABLE foods ADD COLUMN IF NOT EXISTS magnesium REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS phosphorus REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS zinc REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS copper REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS selenium REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS manganese REAL;

-- Fats
ALTER TABLE foods ADD COLUMN IF NOT EXISTS monounsaturated_fat REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS polyunsaturated_fat REAL;

-- Other
ALTER TABLE foods ADD COLUMN IF NOT EXISTS caffeine REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS alcohol REAL;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS water_content REAL;
